"""Fourth migration.

Revision ID: 14d225470019
Revises: 64b65fc12719
Create Date: 2020-07-08 20:40:17.756970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d225470019'
down_revision = '64b65fc12719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dorm',
    sa.Column('dorm_gender', sa.String(length=6), nullable=False),
    sa.Column('dormage_group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('dorm_gender')
    )
    op.add_column('child', sa.Column('dormnum', sa.Integer(), nullable=True))
    op.add_column('parent', sa.Column('dormnum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parent', 'dormnum')
    op.drop_column('child', 'dormnum')
    op.drop_table('dorm')
    # ### end Alembic commands ###
