"""Second migration.

Revision ID: 2544931f2e51
Revises: 9862642aecd3
Create Date: 2020-07-08 17:11:43.876055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2544931f2e51'
down_revision = '9862642aecd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=25), nullable=True),
    sa.Column('lname', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('mname', sa.String(length=30), nullable=True),
    sa.Column('parentname', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('illness', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_table('parent',
    sa.Column('fname', sa.String(length=25), nullable=True),
    sa.Column('lname', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=6), nullable=True),
    sa.Column('parent_email', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('parent_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    op.drop_table('child')
    # ### end Alembic commands ###
