"""Initial migration

Revision ID: 9862642aecd3
Revises: 
Create Date: 2020-07-08 11:34:06.612726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9862642aecd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('webaddress', sa.String(length=255), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('parent')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', mysql.TINYTEXT(), nullable=True),
    sa.Column('password', mysql.TINYTEXT(), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('parent',
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fname', mysql.TINYTEXT(), nullable=True),
    sa.Column('lname', mysql.TINYTEXT(), nullable=True),
    sa.Column('phone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('parent_email', mysql.TINYTEXT(), nullable=True),
    sa.Column('gender', mysql.TINYTEXT(), nullable=True),
    sa.Column('skills', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('parent_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('firstname', mysql.TINYTEXT(), nullable=True),
    sa.Column('lastname', mysql.TINYTEXT(), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('wishlist_item')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
