"""Sixth migration.

Revision ID: a52d9d8bd2fd
Revises: f0d2e5c4aba5
Create Date: 2020-07-08 22:11:42.427969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a52d9d8bd2fd'
down_revision = 'f0d2e5c4aba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dorm', 'dorm_gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dorm', 'dorm_gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    # ### end Alembic commands ###
