"""Fifth migration.

Revision ID: f0d2e5c4aba5
Revises: 14d225470019
Create Date: 2020-07-08 22:06:34.184530

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0d2e5c4aba5'
down_revision = '14d225470019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dorm', sa.Column('dorm_id', sa.Integer(), nullable=False))
    op.alter_column('dorm', 'dorm_gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dorm', 'dorm_gender',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    op.drop_column('dorm', 'dorm_id')
    # ### end Alembic commands ###
